version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/next"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "npm"
    directory: "/apps/laravel"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "composer"
    directory: "/apps/laravel"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "docker"
    directory: "/docker/next"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "docker"
    directory: "/docker/laravel"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
